# Generated by Django 4.0.3 on 2022-05-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Free',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('create_id_user_fr', models.IntegerField(blank=True, null=True)),
                ('comment_NB', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('correction_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_ip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('create_id_user_ip', models.IntegerField(blank=True, null=True)),
                ('comment_ip', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('correction_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('create_id_user_st', models.IntegerField(blank=True, null=True)),
                ('comment_Story', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('correction_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeNoticeBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('context', models.TextField(null=True)),
                ('img1', models.TextField(blank=True, null=True)),
                ('img2', models.TextField(blank=True, null=True)),
                ('img3', models.TextField(blank=True, null=True)),
                ('img4', models.TextField(blank=True, null=True)),
                ('img5', models.TextField(blank=True, null=True)),
                ('create_user', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('correction_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100)),
                ('context', models.TextField()),
                ('create_user_id', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('correction_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('context', models.TextField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='image/Notification/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='image/Notification/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='image/Notification/')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('correction_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryNoticeBoard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('context', models.TextField()),
                ('create_user', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('correction_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='suggestion_free',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('board', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='suggestion_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True, null=True)),
                ('board', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=65)),
            ],
        ),
    ]
